from aiohttp import web

from core.api.control_plane_handler import ControlPlaneHandler
from core.api.xuanwu_proxy_handler import XuanWuProxyHandler

CONFIG_KEY = web.AppKey("config", dict)


def create_http_app(config: dict) -> web.Application:
    app = web.Application()
    app[CONFIG_KEY] = config
    control_plane_handler = ControlPlaneHandler(config)
    xuanwu_proxy_handler = XuanWuProxyHandler(config)
    app.add_routes(
        [
            web.get(
                "/control-plane/v1/config/server",
                control_plane_handler.handle_get_server_config,
            ),
            web.put(
                "/control-plane/v1/config/server",
                control_plane_handler.handle_put_server_config,
            ),
            web.options(
                "/control-plane/v1/config/server",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/users",
                control_plane_handler.handle_list_users,
            ),
            web.post(
                "/control-plane/v1/users",
                control_plane_handler.handle_create_user,
            ),
            web.options(
                "/control-plane/v1/users",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/channels",
                control_plane_handler.handle_list_channels,
            ),
            web.post(
                "/control-plane/v1/channels",
                control_plane_handler.handle_create_channel,
            ),
            web.options(
                "/control-plane/v1/channels",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/events",
                control_plane_handler.handle_list_events,
            ),
            web.post(
                "/control-plane/v1/events",
                control_plane_handler.handle_post_event,
            ),
            web.options(
                "/control-plane/v1/events",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/telemetry",
                control_plane_handler.handle_list_telemetry,
            ),
            web.post(
                "/control-plane/v1/telemetry",
                control_plane_handler.handle_post_telemetry,
            ),
            web.options(
                "/control-plane/v1/telemetry",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/alarms",
                control_plane_handler.handle_list_alarms,
            ),
            web.options(
                "/control-plane/v1/alarms",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/alarms/{alarm_id}:ack",
                control_plane_handler.handle_ack_alarm,
            ),
            web.options(
                "/control-plane/v1/alarms/{alarm_id}:ack",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/gateways",
                control_plane_handler.handle_list_gateways,
            ),
            web.post(
                "/control-plane/v1/gateways",
                control_plane_handler.handle_upsert_gateway,
            ),
            web.options(
                "/control-plane/v1/gateways",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/gateways/{gateway_id}",
                control_plane_handler.handle_get_gateway,
            ),
            web.put(
                "/control-plane/v1/gateways/{gateway_id}",
                control_plane_handler.handle_upsert_gateway,
            ),
            web.options(
                "/control-plane/v1/gateways/{gateway_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/capabilities",
                control_plane_handler.handle_list_capabilities,
            ),
            web.post(
                "/control-plane/v1/capabilities",
                control_plane_handler.handle_create_capability,
            ),
            web.options(
                "/control-plane/v1/capabilities",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/capability-routes",
                control_plane_handler.handle_list_capability_routes,
            ),
            web.post(
                "/control-plane/v1/capability-routes",
                control_plane_handler.handle_create_capability_route,
            ),
            web.options(
                "/control-plane/v1/capability-routes",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/ota/firmwares",
                control_plane_handler.handle_list_firmwares,
            ),
            web.post(
                "/control-plane/v1/ota/firmwares",
                control_plane_handler.handle_upsert_firmware,
            ),
            web.options(
                "/control-plane/v1/ota/firmwares",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/ota/firmwares/{firmware_id}",
                control_plane_handler.handle_get_firmware,
            ),
            web.put(
                "/control-plane/v1/ota/firmwares/{firmware_id}",
                control_plane_handler.handle_upsert_firmware,
            ),
            web.options(
                "/control-plane/v1/ota/firmwares/{firmware_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/ota/campaigns",
                control_plane_handler.handle_list_ota_campaigns,
            ),
            web.post(
                "/control-plane/v1/ota/campaigns",
                control_plane_handler.handle_create_ota_campaign,
            ),
            web.options(
                "/control-plane/v1/ota/campaigns",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/devices",
                control_plane_handler.handle_list_devices,
            ),
            web.post(
                "/control-plane/v1/devices",
                control_plane_handler.handle_create_device,
            ),
            web.options(
                "/control-plane/v1/devices",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/devices/{device_id}",
                control_plane_handler.handle_get_device,
            ),
            web.put(
                "/control-plane/v1/devices/{device_id}",
                control_plane_handler.handle_put_device,
            ),
            web.options(
                "/control-plane/v1/devices/{device_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/agents/{agent_id}",
                control_plane_handler.handle_get_agent,
            ),
            web.put(
                "/control-plane/v1/agents/{agent_id}",
                control_plane_handler.handle_put_agent,
            ),
            web.options(
                "/control-plane/v1/agents/{agent_id}",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/runtime/device-config:resolve",
                control_plane_handler.handle_resolve_device_config,
            ),
            web.options(
                "/control-plane/v1/runtime/device-config:resolve",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/chat-history/report",
                control_plane_handler.handle_report_chat_history,
            ),
            web.options(
                "/control-plane/v1/chat-history/report",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/chat-summaries/{summary_id}:generate",
                control_plane_handler.handle_generate_chat_summary,
            ),
            web.options(
                "/control-plane/v1/chat-summaries/{summary_id}:generate",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/agents",
                xuanwu_proxy_handler.handle_agent_collection,
            ),
            web.post(
                "/control-plane/v1/xuanwu/agents",
                xuanwu_proxy_handler.handle_agent_collection,
            ),
            web.options(
                "/control-plane/v1/xuanwu/agents",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_agent_item,
            ),
            web.put(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_agent_item,
            ),
            web.delete(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_agent_item,
            ),
            web.options(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/model-providers",
                xuanwu_proxy_handler.handle_model_provider_collection,
            ),
            web.post(
                "/control-plane/v1/xuanwu/model-providers",
                xuanwu_proxy_handler.handle_model_provider_collection,
            ),
            web.options(
                "/control-plane/v1/xuanwu/model-providers",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_model_provider_item,
            ),
            web.put(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_model_provider_item,
            ),
            web.delete(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_model_provider_item,
            ),
            web.options(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/models",
                xuanwu_proxy_handler.handle_model_collection,
            ),
            web.post(
                "/control-plane/v1/xuanwu/models",
                xuanwu_proxy_handler.handle_model_collection,
            ),
            web.options(
                "/control-plane/v1/xuanwu/models",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_model_item,
            ),
            web.put(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_model_item,
            ),
            web.delete(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_model_item,
            ),
            web.options(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_options,
            ),
        ]
    )
    return app
