from aiohttp import web

from core.api.control_plane_handler import ControlPlaneHandler
from core.api.xuanwu_proxy_handler import XuanWuProxyHandler

CONFIG_KEY = web.AppKey("config", dict)
CONTROL_PLANE_HANDLER_KEY = web.AppKey("control_plane_handler", ControlPlaneHandler)


def create_http_app(config: dict) -> web.Application:
    app = web.Application()
    app[CONFIG_KEY] = config
    control_plane_handler = ControlPlaneHandler(config)
    xuanwu_proxy_handler = XuanWuProxyHandler(config)
    app[CONTROL_PLANE_HANDLER_KEY] = control_plane_handler
    app.add_routes(
        [
            web.get(
                "/control-plane/v1/config/server",
                control_plane_handler.handle_get_server_config,
            ),
            web.put(
                "/control-plane/v1/config/server",
                control_plane_handler.handle_put_server_config,
            ),
            web.options(
                "/control-plane/v1/config/server",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/auth/login",
                control_plane_handler.handle_login,
            ),
            web.post(
                "/control-plane/v1/auth/logout",
                control_plane_handler.handle_logout,
            ),
            web.get(
                "/control-plane/v1/auth/me",
                control_plane_handler.handle_get_me,
            ),
            web.options(
                "/control-plane/v1/auth/login",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/auth/logout",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/auth/me",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/dashboard/overview",
                control_plane_handler.handle_get_dashboard_overview,
            ),
            web.options(
                "/control-plane/v1/dashboard/overview",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/portal/config",
                control_plane_handler.handle_get_portal_config,
            ),
            web.options(
                "/control-plane/v1/portal/config",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/roles",
                control_plane_handler.handle_list_roles,
            ),
            web.options(
                "/control-plane/v1/roles",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/users",
                control_plane_handler.handle_list_users,
            ),
            web.post(
                "/control-plane/v1/users",
                control_plane_handler.handle_create_user,
            ),
            web.options(
                "/control-plane/v1/users",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/users/{user_id}",
                control_plane_handler.handle_get_user,
            ),
            web.put(
                "/control-plane/v1/users/{user_id}",
                control_plane_handler.handle_put_user,
            ),
            web.delete(
                "/control-plane/v1/users/{user_id}",
                control_plane_handler.handle_delete_user,
            ),
            web.options(
                "/control-plane/v1/users/{user_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/channels",
                control_plane_handler.handle_list_channels,
            ),
            web.post(
                "/control-plane/v1/channels",
                control_plane_handler.handle_create_channel,
            ),
            web.options(
                "/control-plane/v1/channels",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/channels/{channel_id}",
                control_plane_handler.handle_get_channel,
            ),
            web.put(
                "/control-plane/v1/channels/{channel_id}",
                control_plane_handler.handle_put_channel,
            ),
            web.delete(
                "/control-plane/v1/channels/{channel_id}",
                control_plane_handler.handle_delete_channel,
            ),
            web.options(
                "/control-plane/v1/channels/{channel_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/events",
                control_plane_handler.handle_list_events,
            ),
            web.post(
                "/control-plane/v1/events",
                control_plane_handler.handle_post_event,
            ),
            web.get(
                "/control-plane/v1/events/{event_id}",
                control_plane_handler.handle_get_event,
            ),
            web.options(
                "/control-plane/v1/events",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/events/{event_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/telemetry",
                control_plane_handler.handle_list_telemetry,
            ),
            web.post(
                "/control-plane/v1/telemetry",
                control_plane_handler.handle_post_telemetry,
            ),
            web.options(
                "/control-plane/v1/telemetry",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/alarms",
                control_plane_handler.handle_list_alarms,
            ),
            web.get(
                "/control-plane/v1/alarms/{alarm_id}",
                control_plane_handler.handle_get_alarm,
            ),
            web.options(
                "/control-plane/v1/alarms",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/alarms/{alarm_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/alerts/overview",
                control_plane_handler.handle_get_alerts_overview,
            ),
            web.options(
                "/control-plane/v1/alerts/overview",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/alarms/{alarm_id}:ack",
                control_plane_handler.handle_ack_alarm,
            ),
            web.options(
                "/control-plane/v1/alarms/{alarm_id}:ack",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/gateways",
                control_plane_handler.handle_list_gateways,
            ),
            web.get(
                "/control-plane/v1/gateway/overview",
                control_plane_handler.handle_get_gateway_overview,
            ),
            web.post(
                "/control-plane/v1/gateways",
                control_plane_handler.handle_upsert_gateway,
            ),
            web.options(
                "/control-plane/v1/gateways",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/gateway/overview",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/gateways/{gateway_id}",
                control_plane_handler.handle_get_gateway,
            ),
            web.put(
                "/control-plane/v1/gateways/{gateway_id}",
                control_plane_handler.handle_upsert_gateway,
            ),
            web.options(
                "/control-plane/v1/gateways/{gateway_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/user-devices",
                control_plane_handler.handle_list_user_device_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/user-devices",
                control_plane_handler.handle_create_user_device_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/user-devices",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/user-channels",
                control_plane_handler.handle_list_user_channel_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/user-channels",
                control_plane_handler.handle_create_user_channel_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/user-channels",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/channel-devices",
                control_plane_handler.handle_list_channel_device_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/channel-devices",
                control_plane_handler.handle_create_channel_device_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/channel-devices",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/device-agents",
                control_plane_handler.handle_list_device_agent_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/device-agents",
                control_plane_handler.handle_create_device_agent_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/device-agents",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/agent-model-providers",
                control_plane_handler.handle_list_agent_model_provider_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/agent-model-providers",
                control_plane_handler.handle_create_agent_model_provider_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/agent-model-providers",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/agent-model-configs",
                control_plane_handler.handle_list_agent_model_config_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/agent-model-configs",
                control_plane_handler.handle_create_agent_model_config_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/agent-model-configs",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/agent-knowledge",
                control_plane_handler.handle_list_agent_knowledge_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/agent-knowledge",
                control_plane_handler.handle_create_agent_knowledge_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/agent-knowledge",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/mappings/agent-workflows",
                control_plane_handler.handle_list_agent_workflow_mappings,
            ),
            web.post(
                "/control-plane/v1/mappings/agent-workflows",
                control_plane_handler.handle_create_agent_workflow_mapping,
            ),
            web.options(
                "/control-plane/v1/mappings/agent-workflows",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/capabilities",
                control_plane_handler.handle_list_capabilities,
            ),
            web.post(
                "/control-plane/v1/capabilities",
                control_plane_handler.handle_create_capability,
            ),
            web.options(
                "/control-plane/v1/capabilities",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/capability-routes",
                control_plane_handler.handle_list_capability_routes,
            ),
            web.post(
                "/control-plane/v1/capability-routes",
                control_plane_handler.handle_create_capability_route,
            ),
            web.options(
                "/control-plane/v1/capability-routes",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/ota/firmwares",
                control_plane_handler.handle_list_firmwares,
            ),
            web.post(
                "/control-plane/v1/ota/firmwares",
                control_plane_handler.handle_upsert_firmware,
            ),
            web.options(
                "/control-plane/v1/ota/firmwares",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/ota/firmwares/{firmware_id}",
                control_plane_handler.handle_get_firmware,
            ),
            web.put(
                "/control-plane/v1/ota/firmwares/{firmware_id}",
                control_plane_handler.handle_upsert_firmware,
            ),
            web.options(
                "/control-plane/v1/ota/firmwares/{firmware_id}",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/ota/campaigns",
                control_plane_handler.handle_list_ota_campaigns,
            ),
            web.post(
                "/control-plane/v1/ota/campaigns",
                control_plane_handler.handle_create_ota_campaign,
            ),
            web.options(
                "/control-plane/v1/ota/campaigns",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/jobs/schedules",
                control_plane_handler.handle_list_job_schedules,
            ),
            web.get(
                "/control-plane/v1/jobs/schedules/{schedule_id}",
                control_plane_handler.handle_get_job_schedule,
            ),
            web.get(
                "/control-plane/v1/jobs/overview",
                control_plane_handler.handle_get_jobs_overview,
            ),
            web.post(
                "/control-plane/v1/jobs/schedules",
                control_plane_handler.handle_create_job_schedule,
            ),
            web.options(
                "/control-plane/v1/jobs/schedules",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/jobs/schedules/{schedule_id}",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/jobs/overview",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/jobs/schedules:due",
                control_plane_handler.handle_list_due_job_schedules,
            ),
            web.options(
                "/control-plane/v1/jobs/schedules:due",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/jobs/schedules/{schedule_id}:claim",
                control_plane_handler.handle_claim_job_schedule,
            ),
            web.options(
                "/control-plane/v1/jobs/schedules/{schedule_id}:claim",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/jobs:execute",
                control_plane_handler.handle_execute_job,
            ),
            web.options(
                "/control-plane/v1/jobs:execute",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/jobs/runs",
                control_plane_handler.handle_list_job_runs,
            ),
            web.get(
                "/control-plane/v1/jobs/runs/{job_run_id}",
                control_plane_handler.handle_get_job_run,
            ),
            web.options(
                "/control-plane/v1/jobs/runs",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/jobs/runs/{job_run_id}",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/jobs/runs/{job_run_id}:complete",
                control_plane_handler.handle_complete_job_run,
            ),
            web.options(
                "/control-plane/v1/jobs/runs/{job_run_id}:complete",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/jobs/runs/{job_run_id}:fail",
                control_plane_handler.handle_fail_job_run,
            ),
            web.options(
                "/control-plane/v1/jobs/runs/{job_run_id}:fail",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/devices",
                control_plane_handler.handle_list_devices,
            ),
            web.post(
                "/control-plane/v1/devices",
                control_plane_handler.handle_create_device,
            ),
            web.options(
                "/control-plane/v1/devices",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/devices:batch-import",
                control_plane_handler.handle_batch_import_devices,
            ),
            web.options(
                "/control-plane/v1/devices:batch-import",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/devices/{device_id}",
                control_plane_handler.handle_get_device,
            ),
            web.get(
                "/control-plane/v1/devices/{device_id}/detail",
                control_plane_handler.handle_get_device_detail,
            ),
            web.put(
                "/control-plane/v1/devices/{device_id}",
                control_plane_handler.handle_put_device,
            ),
            web.options(
                "/control-plane/v1/devices/{device_id}",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/devices/{device_id}/detail",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/devices/{device_id}:claim",
                control_plane_handler.handle_claim_device,
            ),
            web.options(
                "/control-plane/v1/devices/{device_id}:claim",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/devices/{device_id}:bind",
                control_plane_handler.handle_bind_device,
            ),
            web.options(
                "/control-plane/v1/devices/{device_id}:bind",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/devices/{device_id}:suspend",
                control_plane_handler.handle_suspend_device,
            ),
            web.options(
                "/control-plane/v1/devices/{device_id}:suspend",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/devices/{device_id}:retire",
                control_plane_handler.handle_retire_device,
            ),
            web.options(
                "/control-plane/v1/devices/{device_id}:retire",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/agents/{agent_id}",
                control_plane_handler.handle_get_agent,
            ),
            web.put(
                "/control-plane/v1/agents/{agent_id}",
                control_plane_handler.handle_put_agent,
            ),
            web.options(
                "/control-plane/v1/agents/{agent_id}",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/runtime/device-config:resolve",
                control_plane_handler.handle_resolve_device_config,
            ),
            web.options(
                "/control-plane/v1/runtime/device-config:resolve",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/runtime/devices/{device_id}/binding-view",
                control_plane_handler.handle_get_runtime_binding_view,
            ),
            web.options(
                "/control-plane/v1/runtime/devices/{device_id}/binding-view",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/runtime/devices/{device_id}/capability-routing-view",
                control_plane_handler.handle_get_runtime_capability_routing_view,
            ),
            web.options(
                "/control-plane/v1/runtime/devices/{device_id}/capability-routing-view",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/chat-history/report",
                control_plane_handler.handle_report_chat_history,
            ),
            web.options(
                "/control-plane/v1/chat-history/report",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/chat-summaries/{summary_id}:generate",
                control_plane_handler.handle_generate_chat_summary,
            ),
            web.options(
                "/control-plane/v1/chat-summaries/{summary_id}:generate",
                control_plane_handler.handle_options,
            ),
            web.post(
                "/control-plane/v1/gateway/events",
                control_plane_handler.handle_gateway_event,
            ),
            web.post(
                "/control-plane/v1/gateway/telemetry",
                control_plane_handler.handle_gateway_telemetry,
            ),
            web.post(
                "/control-plane/v1/gateway/command-results",
                control_plane_handler.handle_gateway_command_result,
            ),
            web.options(
                "/control-plane/v1/gateway/events",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/gateway/telemetry",
                control_plane_handler.handle_options,
            ),
            web.options(
                "/control-plane/v1/gateway/command-results",
                control_plane_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/agents",
                xuanwu_proxy_handler.handle_agent_collection,
            ),
            web.post(
                "/control-plane/v1/xuanwu/agents",
                xuanwu_proxy_handler.handle_agent_collection,
            ),
            web.options(
                "/control-plane/v1/xuanwu/agents",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_agent_item,
            ),
            web.put(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_agent_item,
            ),
            web.delete(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_agent_item,
            ),
            web.options(
                "/control-plane/v1/xuanwu/agents/{agent_id}",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/model-providers",
                xuanwu_proxy_handler.handle_model_provider_collection,
            ),
            web.post(
                "/control-plane/v1/xuanwu/model-providers",
                xuanwu_proxy_handler.handle_model_provider_collection,
            ),
            web.options(
                "/control-plane/v1/xuanwu/model-providers",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_model_provider_item,
            ),
            web.put(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_model_provider_item,
            ),
            web.delete(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_model_provider_item,
            ),
            web.options(
                "/control-plane/v1/xuanwu/model-providers/{provider_id}",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/models",
                xuanwu_proxy_handler.handle_model_collection,
            ),
            web.post(
                "/control-plane/v1/xuanwu/models",
                xuanwu_proxy_handler.handle_model_collection,
            ),
            web.options(
                "/control-plane/v1/xuanwu/models",
                xuanwu_proxy_handler.handle_options,
            ),
            web.get(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_model_item,
            ),
            web.put(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_model_item,
            ),
            web.delete(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_model_item,
            ),
            web.options(
                "/control-plane/v1/xuanwu/models/{model_id}",
                xuanwu_proxy_handler.handle_options,
            ),
        ]
    )
    return app
